<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Elvern.VlcOpener</AssemblyName>
    <RootNamespace>Elvern.VlcOpener</RootNamespace>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup Condition="'$(ElvernAllowedOrigin)' != ''">
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>ElvernAllowedOrigin</_Parameter1>
      <_Parameter2>$(ElvernAllowedOrigin)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests/**" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Elvern.VlcOpener.Tests" />
  </ItemGroup>
</Project>
